#!/bin/bash
BASE=/mnt/glibc
IP=${NETPERF_IP:-127.0.0.1}
PORT=${NETPERF_PORT:-12865}

cd "$BASE"

echo "#### OS COMP TEST GROUP START netperf-glibc ####"

run_netperf() {
    local test_name=$1
    local test_args=$2
    local ans=fail

    echo "====== netperf ${test_name} begin ======"
    if ./netperf -H "$IP" -p "$PORT" -t "$test_name" -l 1 -- $test_args; then
        ans=success
    fi
    echo "====== netperf ${test_name} end: ${ans} ======"
}

./netserver -D -L "$IP" -p "$PORT" &
server_pid=$!

sleep 0.5
run_netperf UDP_STREAM "-s 16k -S 16k -m 1k -M 1k"
run_netperf TCP_STREAM "-s 16k -S 16k -m 1k -M 1k"
run_netperf UDP_RR "-s 16k -S 16k -m 1k -M 1k -r 64,64 -R 1"
run_netperf TCP_RR "-s 16k -S 16k -m 1k -M 1k -r 64,64 -R 1"
run_netperf TCP_CRR "-s 16k -S 16k -m 1k -M 1k -r 64,64 -R 1"

kill -9 "$server_pid"


echo "#### OS COMP TEST GROUP END netperf-glibc ####"
